---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aurora-os-custom
# description will be included in the image's metadata
description: Remote managed Aurora OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: latest

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      # Set default wallpapers
      - cp /usr/share/backgrounds/aurora/jonatan-pie-aurora/contents/images/3944x2770.jxl /usr/share/backgrounds/default.jxl
      - cp /usr/share/backgrounds/aurora/jonatan-pie-aurora/contents/images/3944x2770.jxl /usr/share/backgrounds/default-dark.jxl

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    # repos:
    #   copr:
    #     - atim/starship
    install:
      packages:
        - tailscale
        - vlc
    # remove:
    #   packages:
    #     # example: removing firefox (in favor of the flatpak)
    #     # "firefox" is the main package, "firefox-langpacks" is a dependency
    #     - firefox
    #     - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: rpm-ostree
    install:
      - https://github.com/rustdesk/rustdesk/releases/download/1.4.5/rustdesk-1.4.5-0.x86_64.rpm

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.google.Chrome
          - org.libreoffice.LibreOffice
          - org.audacityteam.Audacity
          - com.spotify.Client
          - org.gnome.Loupe
          - org.gimp.GIMP
      # - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
        - tailscaled.service
        - rustdesk.service